### ISSUE TITLE
雙拼該怎麼用這些設置

### ISSUE THREAD

**Issue by liaozhaishusheng** [liuour/rime#1]
多謝你的配置文件，解決了我之前水平豎直和候選字數修改不過來的問題（原來配置方式不一樣了……）

想請問下，雙拼要怎麼使用你提得到這些便利性的設置？像表情，疊字之類的……

**Comment by liuour** [comment]
double_pinyin_flypy.custom.yaml，至于叠字，如果词库里不包含，可以添加在文本替换里。
