### ISSUE TITLE
候选字过多过长，就会分为两行

### ISSUE THREAD

**Issue by ililu2000** [liuour/rime#13]
如图
https://s3.ax1x.com/2021/02/08/yUROfg.png

好像是 0.15 版之后才有的，两行也就算了，一个词组也要分两行显示，有点难看，有什么办法能固定为一行吗

**Comment by liuour** [comment]
请仔细阅读文章内容

ililu2000 <notifications@github.com>于2021年2月8日 周一16:35写道：

**Comment by ililu2000** [comment]
没有看到解决方案😭

**Comment by liuour** [comment]
①这是0.15.0特有功能，支持多行显示，不喜欢的可以回到0.14.0，②可以参考文内设置候选词个数

**Comment by ililu2000** [comment]
多行显示我不介意，像图片这样，第六个词 6 热情，热字在第一行，情字在第二行，很无奈。有办法解决么。一个完整的词组，要么就显示在第一行，要么就显示在第二行。

**Comment by ililu2000** [comment]
https://github.com/rime/squirrel/issues/515
