### ISSUE TITLE
其他输入方式如双拼是否无法使用词库和表情包

### ISSUE THREAD

**Issue by liaozhaishusheng** [liuour/rime#16]
其他输入方式如双拼是否无法使用词库和表情包

**Comment by liuour** [comment]
不会用双拼，所以也没测试过，你加入一个词库试试。

**Comment by liaozhaishusheng** [comment]
> 不会用双拼，所以也没测试过，你加入一个词库试试。

多謝！整了半天，現在可以用了。但是非常不穩定，經常不起作用😂️

**Comment by liuour** [comment]
今天特意了解了下，朙月拼音词库不支持双拼，格式不一致，Emoji 支持

**Comment by ShenJiahuan** [comment]
https://github.com/wongdean/rime-settings
这个配置的词库似乎双拼也可以用，是否有可能把词库格式改成这个样子的呢？
