### ISSUE TITLE
macOS配置后词库无效

### ISSUE THREAD

**Issue by Yangliu233** [liuour/rime#21]
macos下纯净Rime+这套配置，用了几个名词测试词库似乎没有效果，包括网上下载的词库也无效，网上并没有搜索到相关的解决方法
luna_pinyin_simple.custom.yaml中 "translator/dictionary": luna_pinyin.extended 已开启
luna_pinyin.extended.dict.yaml中也正确链接了luna.pinyin/luna.pinyin.sougou/luna.pinyin.zonghe三个路径
除去这个问题之外其他功能都正常使用，是我用过的最好的Rime配置，无论如何感谢作者的辛苦付出！

**Comment by liuour** [comment]
因词库转换为纯汉字无拼音，极少部分词典失效，我正在重新整理词库样式，请稍等。

**Comment by liuour** [comment]
已上传修改后的 `luna_pinyin.sogou.dict.yaml`，请下载并重新部署。

**Comment by Yangliu233** [comment]
> 已上传修改后的 `luna_pinyin.sogou.dict.yaml`，请下载并重新部署。

-下载并重新部署后词库仍然无效
-**完全卸载并重启后重装Rime后测试词库可以正常使用，建议后续遇到这个问题的朋友尝试卸载重装**
-另外踩了一个坑：皮肤设定里修改皮肤时需要填写的皮肤名称是每个皮肤设定的**第一行名字**而非设定中**name所指向的名字**。以幽能/Psionics皮肤为例，应当填写psionics而非Psionics，否则就会使用默认皮肤
