### ISSUE TITLE
医学词典的错误

### ISSUE THREAD

**Issue by iDvel** [liuour/rime#6]
看日志的时候发现全是一堆解析错误，都是从 `luna_pinyin.yixue.dict.yaml` 这个字典里蹦出来的。

已修正错误的空格和Tab。

就不发PR了，可以从我这下载哈
https://github.com/iDvel/rime-settings/blob/master/ext_dict/luna_pinyin.yixue.dict.yaml

**Comment by liuour** [comment]
已测试，未出现错误，词库正常。

**Comment by iDvel** [comment]
从 90059 行 「阿拉伯胶  a la bo jiao  1」开始都是空格了，应该用Tab的。

**Comment by liuour** [comment]
果然有问题，已使用你修复好的，我是用Windows上深蓝词库转换工具直接导出，可能是多个 `txt` 文本导入转换会出错，具体原因不详。
