### ISSUE TITLE
请问default.custom.yaml文件下哪一条规则决定中英文切换，我想更改到以前的shift快速切换中英文。

### ISSUE THREAD

**Issue by AFlyingBird90** [liuour/rime#9]

**Comment by AFlyingBird90** [comment]
# - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}    # 中英文切换

我把这一条取消注释并修改成Shift似乎并不起作用

**Comment by liuour** [comment]
请查看目录四，将Shift_L修改即可

**Comment by AFlyingBird90** [comment]
> 请查看目录四，将Shift_L修改即可

原来如此，谢谢，搞定了。刚发现master文件夹里的default.custom.yaml内容跟readme里目录四的截图内容不一样。
